FACEBOOK_PAGE_ACCESS_TOKEN=<FBaccessToken>
FACEBOOK_PAGE_ID=<FBpageID>


#FACEBOOK_PAGE_ACCESS_TOKEN=<FBaccessToken>
#FACEBOOK_PAGE_ID=<FBpageID>

PINTEREST_BOARD_ID=<pinterestBoardID>
PINTEREST_ACCESS_TOKEN=<pinterest_accss_token>


CLARIFAI_API_KEY=<clarifai_apikey>
